site_name: Attach-To-Me for VRChat
nav:
  - Index: index.md
  - English: 
    - Overview: en/index.md
    - 'Upgrade guide': en/upgrade.md
  - 日本語:
    - 概要: jp/index.md
    - 更新ガイド: jp/upgrade.md
theme:
  name: 'material'
site_url: "https://bdunderscore.github.io/attach-to-me/"
site_name: 'AttachToMe manual'
site_description: 'AttachToMe manual'
site_author: 'bd_'
repo_name: 'bdunderscore/attach-to-me'
repo_url: 'https://github.com/bdunderscore/attach-to-me'