name: Build release artifacts

on: push

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate filelists
        run: |
          echo "Assets/bd_.meta" >> metaList
          echo "Assets/bd_/AttachToMe.meta" >> metaList
          find Assets/bd_/AttachToMe -name '*.meta' >> metaList
      - name: Misc setup
        run: |
          cp LICENSE.txt Assets/bd_/AttachToMe/LICENSE.txt
          mkdir output
          cp LICENSE.txt output
      - name: Build unitypackage
        uses: pCYSl5EDgo/create-unitypackage@2f4ac82dabd3a1029f7a6771f30dc796e4217551
        with:
          package-path: 'output/AttachToMe-dev.unitypackage'
          include-files: metaList
      - name: Upload commit artifacts (dev .zip package)
        uses: actions/upload-artifact@master
        with:
          path: output
          name: AttachToMe-dev
      - name: Set version based on tag
        id: version
        if: startsWith(github.event.ref, 'refs/tags/')
        run: |
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Rename and zip artifacts
        if: startsWith(github.event.ref, 'refs/tags/')
        run: |
          mv output/AttachToMe-dev.unitypackage output/AttachToMe-${{ steps.version.outputs.version }}.unitypackage
          (cd output; zip ../AttachToMe-dev.zip *)
      - name: Create draft release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload unitypackage release artifact
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/AttachToMe-${{ steps.version.outputs.version }}.unitypackage
          asset_name: AttachToMe-${{ steps.version.outputs.version }}.unitypackage
          asset_content_type: application/octet-stream
      - name: Upload zip release artifact
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: AttachToMe-dev.zip
          asset_name: AttachToMe-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip